project:
  type: website

website:
  title: "shiftR"
  page-navigation: true
  back-to-top-navigation: true
  repo-url: https://github.com/ahasoplakus/shifter
  repo-branch: main
  repo-actions: [source, issue]
  navbar:
    left:
      - href: index.qmd
        text: Introduction
      - href: shift.qmd
        text: Shift Table in R
     # - href: about.qmd
      #  icon: question-circle

format:
  html:
    theme: cosmo
    smooth-scroll: true
    css: styles.css
    toc: true
    toc-location: left
    toc_float: false
    page-layout: full
    code-fold: show

editor: visual

