project:
  type: website

website:
  title: "shiftR"
  page-navigation: true
  back-to-top-navigation: true
  repo-url: https://github.com/ahasoplakus/shifter/
  repo-branch: main
  repo-actions: [edit, source]

  page-footer:
    right: "This site is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-By Sukalpo Saha, 2024"
        
  sidebar:
    logo: "img/hex-shiftR.png"
    pinned: true
    align: center
    tools: 
      - icon: github
        href: https://github.com/ahasoplakus/
    style: "docked"
    search: false
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Introduction
      - href: shift.qmd
        text: Creating a Shift Table in R
      - href: about.qmd
        text: References

format:
  html:
    theme: cosmo
    smooth-scroll: true
    css: styles.css
    toc: true
    toc_float: false
    code-fold: show
    code-overflow: wrap
    page-layout: full

editor: visual

