project:
  type: website

website:
  title: "shift2R"
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Introduction
        icon: house
      - href: shift.qmd
        text: R Workflow
        icon: code
     # - href: about.qmd
      #  icon: question-circle
    right:
      - href: https://github.com/ahasoplakus/shifter
        icon: github

format:
  html:
    theme: cosmo
    smooth-scroll: true
    css: styles.css
    toc: true
    toc-location: left
    toc_float: false
    page-layout: full
    code-fold: show

editor: visual

