project:
  type: website

website:
  title: "shift2R"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: yeti
    css: styles.css
    toc: true
    toc_float: false

editor: visual

