project:
  type: website

website:
  title: "shiftR"
  page-navigation: true
  back-to-top-navigation: true
  repo-url: https://github.com/ahasoplakus/shifter/
  repo-branch: main
  repo-actions: [edit, source]

  page-footer:
    right: "This site is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-By Sukalpo Saha, 2024"
        
  sidebar:
    logo: "img/hex-shiftR.png"
    background: light
    pinned: true
    align: center
    tools: 
      - icon: github
        href: https://github.com/ahasoplakus/
      - icon: linkedin
        href: https://www.linkedin.com/in/sukalpo-saha-186329b1/
      - icon: twitter
        href: https://twitter.com/saha_sukalpo/
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Introduction
        icon: house-door-fill
      - href: shift.qmd
        text: Shift Table in R
        icon: code-slash
      - href: about.qmd
        text: About
        icon: info-square

format:
  html:
    theme: cosmo
    smooth-scroll: true
    css: styles.css
    toc: true
    toc_float: false
    code-fold: show
    code-overflow: wrap
    page-layout: full

editor: visual

