project:
  type: website

website:
  title: "shift2R"
  navbar:
    left:
      - href: index.qmd
        text: Introduction
        icon: house
      - href: shift.qmd
        text: Shift Table
        icon: code
      - href: about.qmd
        icon: question-circle
      - href: https://github.com/ahasoplakus/shifter
        text: Source
        icon: github

format:
  html:
    theme: yeti
    smooth-scroll: true
    css: styles.css
    toc: true
    toc-location: left

editor: visual

